### PR TITLE
Fixed nill pointer dereference when running in client mode

### LINKED ISSUE #35: Running consent store in client mode triggers a nillptr dereference
```
$ NUTS_CSTORE_MODE=client NUTS_AUTH_MODE=client ./nuts-go registry register-vendor
...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x46a1241]
```

### PR DESCRIPTION
**Pull request by reinkrul**
Fixes #35

### CODE REVIEW

**Review by woutslakhorst — APPROVED** [review]
To be clear: the used client mode is not yet the 'global' client mode?

**Comment by reinkrul** [comment]
> To be clear: the used client mode is not yet the 'global' client mode?

It might be. The idea is that when you specify the mode globally, the engines inherit that mode (client/server), unless you specify it for the engine (in this case NUTS_CSTORE_MODE).

**Comment by woutslakhorst** [comment]
yes but not part of this PR so it can be ported to 0.12.1

**Comment by reinkrul** [comment]
> yes but not part of this PR so it can be ported to 0.12.1

This was broken pre 0.12 (and apparently ever noticed) so maybe just fix it in 0.13?

**Pull request merged**
